spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:8090
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: job
          uri: http://localhost:8091
          predicates:
            - Path=/job/**
          filters:
            - StripPrefix=1
        - id: payment
          uri: http://localhost:8092
          predicates:
            - Path=/payment/**
          filters:
            - StripPrefix=1
        - id: notification
          uri: http://localhost:8093
          predicates:
            - Path=/notification/**
          filters:
            - StripPrefix=1
        - id: messaging
          uri: http://localhost:8094
          predicates:
            - Path=/messaging/**
          filters:
            - StripPrefix=1
server:
  port: 8080
